create table public.contas_bancarias (
  id_conta integer generated by default as identity not null,
  id_usuario integer not null,
  tipo_conta character varying(20) not null,
  codigo_conta integer null,
  nome_instituicao character varying(100) null,
  nome_conta character varying(100) not null,
  data_criacao timestamp with time zone not null default now(),
  status_conta character varying(10) not null default 'Ativo'::character varying,
  data_inativacao timestamp with time zone null,
  constraint contas_bancarias_pkey primary key (id_conta),
  constraint fk_contas_bancarias_usuario foreign KEY (id_usuario) references usuarios (id_usuario) on delete CASCADE,
  constraint chk_status_conta check (
    (
      (status_conta)::text = any (
        (
          array[
            'Ativo'::character varying,
            'Inativo'::character varying
          ]
        )::text[]
      )
    )
  ),
  constraint chk_tipo_conta check (
    (
      (tipo_conta)::text = any (
        (
          array[
            'Corrente'::character varying,
            'Poupança'::character varying,
            'Salario'::character varying,
            'Conjunta'::character varying,
            'Internacional'::character varying,
            'Credito'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

create unique INDEX IF not exists uq_conta_padrao_usuario on public.contas_bancarias using btree (id_usuario) TABLESPACE pg_default
where
  ((nome_conta)::text = 'padrão'::text);
